version: '3.9'

services:
  backend:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://EuroHoopAdmin:stby9ZGGGqahFyZz@igorcluster.loyvk.mongodb.net/EuroHoopDb
      - REDIS_URL=redis-17861.c245.us-east-1-3.ec2.redns.redis-cloud.com:17861
    depends_on:
      - redis
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: gunicorn -k eventlet -w 1 -b 0.0.0.0:5000 --log-level=debug --access-logfile=- --error-logfile=- run:app

  redis:
    image: redis:7
    ports:
      - "6379:6379"